name: test-install

on: [push]

jobs:

  ubuntu-18-04:
    runs-on: ubuntu-latest
    container: 'ubuntu:18.04'
    steps:
      - name: Requirements
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get upgrade -y
          apt-get install -y wget make libfile-copy-recursive-perl g++ python cpio rpm2cpio curl lsb-release
      - uses: actions/checkout@v2
      - name: Run icommands-install.sh
        run: ./.github/scripts/install.sh
        shell: bash
      - name: Test icommands
        run: ./.github/scripts/test.sh
        shell: bash

  ubuntu-20-04:
    runs-on: ubuntu-latest
    container: 'ubuntu:20.04'
    steps:
      - name: Requirements
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get upgrade -y
          apt-get install -y wget make libfile-copy-recursive-perl g++ python cpio rpm2cpio curl lsb-release
      - uses: actions/checkout@v2
      - name: Run icommands-install.sh
        run: ./.github/scripts/install.sh
        shell: bash
      - name: Test icommands
        run: ./.github/scripts/test.sh
        shell: bash

# Ubuntu 22.04 failed:
# ils: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
#
# Ubuntu 22.04 has dropped libssl1.1 in favour of libssl3 (see OpenSSL 3.0 transition plans for reference),
#
# See later (stable release not published), how to fix it
#
#  ubuntu-22-04:
#    runs-on: ubuntu-latest
#    container: 'ubuntu:22.04'
#    steps:
#      - name: Requirements
#        run: |
#          export DEBIAN_FRONTEND=noninteractive
#          apt-get update
#          apt-get upgrade -y
#          apt-get install -y wget make libfile-copy-recursive-perl g++ python3 cpio rpm2cpio curl lsb-release libssl1.1
#      - uses: actions/checkout@v2
#      - name: Run icommands-install.sh
#        run: ./.github/scripts/install.sh
#        shell: bash
#      - name: Test icommands
#        run: ./.github/scripts/test.sh
#        shell: bash

  rockylinux-8-5:
    runs-on: ubuntu-latest
    container: 'rockylinux:8.5'
    steps:
      - name: Requirements
        run: |
          yum update -y
          # compat-openssl10 to avoid "error while loading shared libraries: libssl.so.10"
          yum install -y -q  wget cpio make findutils compat-openssl10 openssl3-libs
      - uses: actions/checkout@v2
      - name: Run icommands-install.sh
        run: ./.github/scripts/install.sh
        shell: bash
      - name: Test icommands
        run: ./.github/scripts/test.sh
        shell: bash

  rockylinux-9-3:
    runs-on: ubuntu-latest
    container: 'rockylinux:9.3'
    steps:
      - name: Requirements
        run: |
          yum update -y
          # openssl-libs to avoid "error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or directory"
          yum install -y -q wget cpio make findutils openssl-libs
      - uses: actions/checkout@v2
      - name: Run icommands-install.sh
        run: ./.github/scripts/install.sh
        shell: bash
      - name: Test icommands
        run: ./.github/scripts/test.sh
        shell: bash
