name: test-mcia-irods-client-install

on: [push]

jobs:

  ubuntu-1804:
    runs-on: ubuntu-18.04
    steps:
      - name: install requirements
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y wget make libfile-copy-recursive-perl g++ python cpio rpm2cpio curl lsb-release
      - name: Execute icommands-install.sh
        run: |
          # Script should *not* be run as root.
          sudo useradd -s /bin/bash -m -p test test
          sudo su - test
          export prefix=$HOME/local/irods
          wget https://raw.githubusercontent.com/mesocentre-mcia/mcia-irods-client-install/irods4/icommands-install.sh
          chmod a+x icommands-install.sh
          ./icommands-install.sh --prefix $prefix
      - name: test icommand installation
        run: |
          export prefix=$HOME/local/irods
          source $prefix/share/irods/bashrc
          ils -h
