name: test-install

on: [push]

jobs:

  ubuntu-18-04:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["ubuntu:18.04", "ubuntu:20.04"]
    container: "${{ matrix.container }}"
    steps:
      - name: install requirements
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get upgrade -y
          apt-get install -y wget make libfile-copy-recursive-perl g++ python cpio rpm2cpio curl lsb-release
      - name: Run icommands-install.sh
        run: ./.github/scripts/install.sh
        shell: bash
      - name: Test icommands
        run: ./.github/scripts/test.sh
        shell: bash

  ubuntu-22-04:
    runs-on: ubuntu-latest
    container: 'ubuntu:22.04'
    steps:
      - name: Requirements
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get upgrade -y
          apt-get install -y wget make libfile-copy-recursive-perl g++ python3 cpio rpm2cpio curl lsb-release libssl1.1
      - name: Run icommands-install.sh
        run: ./.github/scripts/install.sh
        shell: bash
      - name: Test icommands
        run: ./.github/scripts/test.sh
        shell: bash

  rockylinux-8-5:
    runs-on: ubuntu-latest
    container: 'rockylinux:8.5'
    steps:
      - name: Requirements
        run: |
          yum update -y
          # compat-openssl10 to avoid "error while loading shared libraries: libssl.so.10"
          yum install -y -q  wget cpio make findutils compat-openssl10
      - name: Run icommands-install.sh
        run: ./.github/scripts/install.sh
        shell: bash
      - name: Test icommands
        run: ./.github/scripts/test.sh
        shell: bash
