name: test-install

on: [push]

jobs:

  ubuntu-18-04:
    runs-on: ubuntu-18.04
    steps:
      - name: install requirements
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y wget make libfile-copy-recursive-perl g++ python cpio rpm2cpio curl lsb-release
      - name: execute icommands-install.sh
        run: |
          echo '# Use user test'
          # Script should *not* be run as root.
          sudo useradd -s /bin/bash -m -p test test
          sudo su - test
          export prefix=$HOME/local/irods
          echo '# Download icommands-install.sh script'
          wget https://raw.githubusercontent.com/mesocentre-mcia/mcia-irods-client-install/irods4/icommands-install.sh
          chmod a+x icommands-install.sh
          echo "# Execute icommands-install.sh script (prefix=$prefix)"
          ./icommands-install.sh --prefix $prefix
      - name: test icommand installation
        run: |
          export prefix=$HOME/local/irods
          echo "# Source $prefix/share/irods/bashrc"
          source $prefix/share/irods/bashrc
          echo '# Release:'
          cat /etc/lsb-release
          echo '# ils -h'
          ils -h

  ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
      - name: install requirements
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y wget make libfile-copy-recursive-perl g++ python cpio rpm2cpio curl lsb-release
      - name: execute icommands-install.sh
        run: |
          echo '# Use user test'
          # Script should *not* be run as root.
          sudo useradd -s /bin/bash -m -p test test
          sudo su - test
          export prefix=$HOME/local/irods
          echo '# Download icommands-install.sh script'
          wget https://raw.githubusercontent.com/mesocentre-mcia/mcia-irods-client-install/irods4/icommands-install.sh
          chmod a+x icommands-install.sh
          echo "# Execute icommands-install.sh script (prefix=$prefix)"
          ./icommands-install.sh --prefix $prefix
      - name: test icommand installation
        run: |
          export prefix=$HOME/local/irods
          echo "# Source $prefix/share/irods/bashrc"
          source $prefix/share/irods/bashrc
          echo '# Release:'
          cat /etc/lsb-release
          echo '# ils -h'
          ils -h

  ubuntu-22-04:
    runs-on: ubuntu-20.04
    container: 'ubuntu:22.04'
    steps:
      - name: install requirements
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y wget make libfile-copy-recursive-perl g++ python3 cpio rpm2cpio curl lsb-release libssl1.1
      - name: execute icommands-install.sh
        run: |
          echo '# Use user test'
          # Script should *not* be run as root.
          sudo useradd -s /bin/bash -m -p test test
          sudo su - test
          export prefix=$HOME/local/irods
          echo '# Download icommands-install.sh script'
          wget https://raw.githubusercontent.com/mesocentre-mcia/mcia-irods-client-install/irods4/icommands-install.sh
          chmod a+x icommands-install.sh
          echo "# Execute icommands-install.sh script (prefix=$prefix)"
          ./icommands-install.sh --prefix $prefix
      - name: test icommand installation
        run: |
          export prefix=$HOME/local/irods
          echo "# Source $prefix/share/irods/bashrc"
          source $prefix/share/irods/bashrc
          echo '# Release:'
          cat /etc/lsb-release
          echo '# ils -h'
          ils -h

  rockylinux-8-5:
    runs-on: ubuntu-20.04
    container: 'rockylinux:8.5'
    steps:
      - name: install requirements
        run: |
          yum update -y
          # compat-openssl10 to avoid "error while loading shared libraries: libssl.so.10"
          yum install -y -q  wget cpio make findutils compat-openssl10
      - name: execute icommands-install.sh
        run: |
          echo '# Use user test'
          # Script should *not* be run as root.
          useradd -s /bin/bash -m -p test test
          su - test
          export prefix=$HOME/local/irods
          echo '# Download icommands-install.sh script'
          wget https://raw.githubusercontent.com/mesocentre-mcia/mcia-irods-client-install/irods4/icommands-install.sh
          chmod a+x icommands-install.sh
          echo "# Execute icommands-install.sh script (prefix=$prefix)"
          ./icommands-install.sh --prefix $prefix
      - name: test icommand installation
        run: |
          export prefix=$HOME/local/irods
          echo "# Source $prefix/share/irods/bashrc"
          source $prefix/share/irods/bashrc
          echo '# Release:'
          cat /etc/redhat-release
          echo '# Release:'
          ils -h
