name: test-install

on: [push]

jobs:

  ubuntu-20-04:
    runs-on: ubuntu-latest
    container: 'ubuntu:20.04'
    steps:
      - name: Requirements
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get upgrade -y
          apt-get install -y wget make libfile-copy-recursive-perl g++ python cpio rpm2cpio curl lsb-release libcurl3-gnutls
      - uses: actions/checkout@v2
      - name: Run icommands-install.sh
        run: ./.github/scripts/install.sh
        shell: bash
      - name: Test icommands
        run: ./.github/scripts/test.sh
        shell: bash

  ubuntu-22-04:
   runs-on: ubuntu-latest
   container: 'ubuntu:22.04'
   steps:
     - name: Requirements
       run: |
         export DEBIAN_FRONTEND=noninteractive
         apt-get update
         apt-get upgrade -y
         apt-get install -y wget make libfile-copy-recursive-perl g++ python3 cpio rpm2cpio curl lsb-release libssl-dev libcurl3-gnutls
     - uses: actions/checkout@v2
     - name: Run icommands-install.sh
       run: ./.github/scripts/install.sh
       shell: bash
     - name: Test icommands
       run: ./.github/scripts/test.sh
       shell: bash

  ubuntu-24-04:
    runs-on: ubuntu-latest
    container: 'ubuntu:24.04'
    steps:
      - name: Requirements
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get upgrade -y
          apt-get install -y wget make libfile-copy-recursive-perl g++ python3 cpio rpm2cpio curl lsb-release libssl-dev libcurl3t64-gnutls
      - uses: actions/checkout@v2
      - name: Run icommands-install.sh
        run: ./.github/scripts/install.sh
        shell: bash
      - name: Test icommands
        run: ./.github/scripts/test.sh
        shell: bash

  rockylinux-8-5:
    runs-on: ubuntu-latest
    container: 'rockylinux:8.5'
    steps:
      - name: Requirements
        run: |
          dnf update -y
          dnf install -y epel-release
          # compat-openssl10 to avoid "error while loading shared libraries: libssl.so.10"
          dnf install -y -q redhat-lsb-core wget cpio make findutils compat-openssl10 openssl3-libs
      - uses: actions/checkout@v2
      - name: Run icommands-install.sh
        run: ./.github/scripts/install.sh
        shell: bash
      - name: Test icommands
        run: ./.github/scripts/test.sh
        shell: bash

  rockylinux-9-3:
    runs-on: ubuntu-latest
    container: 'rockylinux:9.3'
    steps:
      - name: Requirements
        run: |
          dnf update -y
          dnf install -y epel-release
          # openssl-libs to avoid "error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or directory"
          dnf install -y -q lsb_release wget cpio make findutils openssl-libs
      - uses: actions/checkout@v2
      - name: Run icommands-install.sh
        run: ./.github/scripts/install.sh
        shell: bash
      - name: Test icommands
        run: ./.github/scripts/test.sh
        shell: bash
